title: Anjolaoluwa Ajayi
description: Data Scientist & ML Engineer
# logo: https://www.datascienceportfol.io/static/profile_pics/pr0_7DAD353255ED8CDA95E3.jpg
show_downloads: false
theme: jekyll-theme-modernist
